// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v4.25.9
// source: review.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Timestamp } from "./google/protobuf/timestamp";

export const protobufPackage = "udemy.reviews.v1";

export interface Review {
  id: string;
  courseId: string;
  userId: string;
  rating: number;
  comment: string;
  createdAt: Timestamp | undefined;
}

export interface CreateReviewRequest {
  courseId: string;
  rating: number;
  comment: string;
}

export interface GetReviewRequest {
  id: string;
}

export interface ReviewResponse {
  review: Review | undefined;
}

export interface UpdateReviewRequest {
  id: string;
  rating?: number | undefined;
  comment?: string | undefined;
}

export interface DeleteReviewRequest {
  id: string;
}

export interface DeleteReviewResponse {
  success: boolean;
}

export interface ListCourseReviewsRequest {
  courseId: string;
}

export interface ListCourseReviewsResponse {
  reviews: Review[];
}

export const UDEMY_REVIEWS_V1_PACKAGE_NAME = "udemy.reviews.v1";

export interface ReviewServiceClient {
  createReview(request: CreateReviewRequest): Observable<ReviewResponse>;

  getReview(request: GetReviewRequest): Observable<ReviewResponse>;

  updateReview(request: UpdateReviewRequest): Observable<ReviewResponse>;

  deleteReview(request: DeleteReviewRequest): Observable<ReviewResponse>;

  listCourseReviews(request: ListCourseReviewsRequest): Observable<ListCourseReviewsResponse>;
}

export interface ReviewServiceController {
  createReview(request: CreateReviewRequest): Promise<ReviewResponse> | Observable<ReviewResponse> | ReviewResponse;

  getReview(request: GetReviewRequest): Promise<ReviewResponse> | Observable<ReviewResponse> | ReviewResponse;

  updateReview(request: UpdateReviewRequest): Promise<ReviewResponse> | Observable<ReviewResponse> | ReviewResponse;

  deleteReview(request: DeleteReviewRequest): Promise<ReviewResponse> | Observable<ReviewResponse> | ReviewResponse;

  listCourseReviews(
    request: ListCourseReviewsRequest,
  ): Promise<ListCourseReviewsResponse> | Observable<ListCourseReviewsResponse> | ListCourseReviewsResponse;
}

export function ReviewServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createReview", "getReview", "updateReview", "deleteReview", "listCourseReviews"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ReviewService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ReviewService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const REVIEW_SERVICE_NAME = "ReviewService";
